import os

samples = {}
config_file = "config/samples.tsv"
SAMPLES = ["amostra_teste"]

if os.path.exists(config_file):
    with open(config_file, "r") as f:
        
        next(f) 
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 2:
                samples[parts[0]] = parts[1]
else:
    print(f"\n--- ERRO: Ficheiro {config_file} não encontrado! ---\n")

rule all:
    input:
        expand("results/anotacao/{amostra}", amostra=SAMPLES),
        expand("results/metaeuk/{amostra}/resultados.fas", amostra=SAMPLES)

rule anotar_bacterias:
    input:
        fasta=lambda wildcards: samples[wildcards.amostra]
    output:
        outdir=directory("results/anotacao/{amostra}")
    log:
        "logs/prokka_{amostra}.log"
    threads: 2
    params:
        prefix="resultado_final"
    wrapper:
        "file://../snakemake-wrappers/bio/prokka"


rule correr_metaeuk:
    input:
        contigs="data/{amostra}.fasta",
        # Agora sim, apontamos para o dicionário verdadeiro!
        db="data/db/uniprot_sprot.fasta" 
    output:
        fas="results/metaeuk/{amostra}/resultados.fas"
    params:
        out_prefix="results/metaeuk/{amostra}/resultados",
        tmp_dir="results/metaeuk/{amostra}/tmp_metaeuk"
    threads: 2
    wrapper:
        "file://../snakemake-wrappers/bio/metaeuk"
        