import os

samples = {}
config_file = "config/samples.tsv"
SAMPLES = ["amostra_teste"]

if os.path.exists(config_file):
    with open(config_file, "r") as f:
        next(f) 
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 2:
                samples[parts[0]] = parts[1]
else:
    print(f"\n--- ERRO: Ficheiro {config_file} não encontrado! ---\n")

rule all:
    input:
        expand("results/anotacao/{amostra}/resultado_final.gff", amostra=SAMPLES),
        expand("results/anotacao/{amostra}/resultado_final.faa", amostra=SAMPLES),
        expand("results/metaeuk/{amostra}/resultados.fas", amostra=SAMPLES)

rule anotar_bacterias:
    input:
        fasta=lambda wildcards: samples[wildcards.amostra]
    output:
        gff="results/anotacao/{amostra}/resultado_final.gff",
        faa="results/anotacao/{amostra}/resultado_final.faa"
    log:
        "logs/prokka_{amostra}.log"
    threads: 2
    params:
        extra="" 
    wrapper:
        "file:///mnt/c/Users/rodol/OneDrive/Documentos/GitHub/snakemake-wrappers/bio/prokka"


rule correr_metaeuk:
    input:
        fasta="data/{amostra}.fasta", 
        db="data/db/uniprot_sprot.fasta" 
    output:
        fas="results/metaeuk/{amostra}/resultados.fas"
    params:
        extra="" 
    threads: 2
    wrapper:
        "file:///mnt/c/Users/rodol/OneDrive/Documentos/GitHub/snakemake-wrappers/bio/metaeuk"
        